apiVersion: apps/v1
kind: Deployment
metadata:
  name: bee-hive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bee-hive
  template:
    metadata:
      labels:
        app: bee-hive
    spec:
      containers:
      - name: bee-hive
        image: bee-hive:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: DUMMY
          value: dummyvalue
---
apiVersion: v1
kind: Service
metadata:
  name: bee-hive
spec:
  selector:
    app: bee-hive
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
